# Generated by Django 4.2.27 on 2026-01-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VoiceToImage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicetask",
            name="baidu_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
