# Generated by Django 4.2.27 on 2026-01-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VoiceToImage", "0002_voicetask_baidu_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voicetask",
            name="baidu_task_id",
        ),
    ]
