# Generated by Django 4.2.27 on 2026-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VoiceToImage", "0003_remove_voicetask_baidu_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicetask",
            name="baidu_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="voicetask",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("简笔画", "简笔画"),
                    ("线稿", "线稿"),
                    ("素描", "素描"),
                    ("动漫", "动漫"),
                    ("卡通", "卡通"),
                    ("水墨", "水墨"),
                ],
                default="卡通",
                max_length=20,
                null=True,
            ),
        ),
    ]
