# Generated by Django 4.2.27 on 2026-03-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Device", "0002_alter_device_product_model"),
        ("VoiceToImage", "0004_voicetask_baidu_task_id_voicetask_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicetask",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_tasks",
                to="Device.device",
            ),
        ),
    ]
