[uwsgi]
chdir=/home/ubuntu/E100DictServer/
virtualenv = /home/ubuntu/E100DictServer/SiteEnv

env=DJANGO_SETTINGS_MODULE=E100DictServer.settings


#本机使用的socket  LYYDownloader    127.0.0.1:29000
socket = /home/ubuntu/E100DictServer/server.sock
#socket = 127.0.0.1:29000


#For all practical serving deployments it is generally a good idea to use master mode.
master = true

safe-pidfile=/home/ubuntu/E100DictServer/E100DictServer.pid

# Django's wsgi file
module          = E100DictServer.wsgi

processes=1# maximum number of worker processes
#gid=MyGroup
harakiri=20 # Every request that will take longer than the seconds specified in the harakiri timeout will be dropped and the corresponding worker is thereafter recycled.
max-requests=500 # Reload workers after the specified amount of managed requests (avoid memory leaks).
#buffer-size=32768#By default uWSGI allocates a very small buffer (4096 bytes) for the headers of each request. If you start receiving “invalid request block size” in your logs, it could mean you need a bigger buffer. Increase it (up to 65535) with the buffer-size option.
#try to remove all of the generated file/sockets
vacuum = true

# background the process & log
daemonize = /home/ubuntu/E100DictServer/E100DictServer_uwsgi.log
#log-maxsize = 6048  设置了会有非常多backup
# log-reopen = true

#map mountpoint to static directory (or file)
static-map =/static=/home/ubuntu/E100DictServer/static
