# Generated by Django 2.1.1 on 2018-10-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewWordCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, unique=True)),
                ('amPhoneticSymbol', models.CharField(blank=True, default='', max_length=30)),
                ('ukPhoneticSymbol', models.CharField(blank=True, default='', max_length=30)),
                ('chineseMeaning', models.TextField(blank=True, default='')),
                ('rawInfo', models.TextField(blank=True, default='')),
            ],
        ),
    ]
