# Generated by Django 2.1.1 on 2018-10-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewWordCard',
            new_name='WordDefinition',
        ),
    ]
