# Generated by Django 2.1.1 on 2018-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0002_auto_20181031_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddefinition',
            name='word',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
