# Generated by Django 2.1.1 on 2018-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0004_auto_20181031_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddefinition',
            name='amPhoneticSymbol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='ukPhoneticSymbol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
