# Generated by Django 2.1.1 on 2019-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0005_auto_20181031_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddefinition',
            name='lemma',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
