# Generated by Django 2.1.1 on 2019-05-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0006_worddefinition_lemma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddefinition',
            name='rawInfo',
        ),
    ]
