# Generated by Django 2.2.2 on 2019-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0007_remove_worddefinition_rawinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worddefinition',
            old_name='chineseMeaning',
            new_name='chineseDefinition',
        ),
        migrations.RenameField(
            model_name='worddefinition',
            old_name='amPhoneticSymbol',
            new_name='ukPhoneticSymbol',
        ),
        migrations.RenameField(
            model_name='worddefinition',
            old_name='ukPhoneticSymbol',
            new_name='usPhoneticSymbol',
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='rawInfo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
