# Generated by Django 2.2.2 on 2019-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0008_auto_20190612_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddefinition',
            name='chineseDefinition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='rawInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
