# Generated by Django 2.2.2 on 2019-06-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0009_auto_20190612_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddefinition',
            name='rawInfo',
        ),
    ]
