# Generated by Django 2.2.2 on 2019-06-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0010_remove_worddefinition_rawinfo'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='worddefinition',
        #     name='chineseDefinition',
        # ),
        # migrations.RemoveField(
        #     model_name='worddefinition',
        #     name='ukPhoneticSymbol',
        # ),
        # migrations.RemoveField(
        #     model_name='worddefinition',
        #     name='usPhoneticSymbol',
        # ),
    ]
