# Generated by Django 2.2.2 on 2019-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDefinition', '0011_auto_20190615_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddefinition',
            name='chineseDefinition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='ukPhoneticSymbol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='usPhoneticSymbol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
