# Generated by Django 4.2.27 on 2026-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WordDefinition", "0012_auto_20190615_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worddefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
