# Generated by Django 4.2.27 on 2026-03-11 03:01

import Device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_model", models.CharField(max_length=64)),
                ("device_id", models.CharField(max_length=128, unique=True)),
                (
                    "device_secret",
                    models.CharField(
                        default=Device.models.generate_secret, max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
