# Generated by Django 4.2.27 on 2026-03-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="product_model",
            field=models.CharField(max_length=10),
        ),
    ]
