"""
Django settings for E100DictServer project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os,sys
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+nkivu&j7#rpd!lnj5ojgv^&v+2$(j4129q)*-l=20m*hol1^0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True#sys.platform == "win32"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "rest_framework",
    'rest_framework_simplejwt',
    # "dicts.apps.DictsConfig",
    # 'WordDefinition.apps.WorddefinitionConfig',
    'VoiceToImage.apps.VoicetoimageConfig',
    'ChatBot.apps.ChatbotConfig',

    'Device.apps.DeviceConfig',
    'image2video.apps.Image2VideoConfig',

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "E100DictServer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "E100DictServer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
    # ,
    # "ecdict": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "WCapture.lib",
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE ='Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_POOL = 'solo'
CELERY_WORKER_CONCURRENCY = 1


# Alibaba DashScope API Key (Qwen-Image)
DASHSCOPE_API_KEY = "sk-73223fb139e147b690aa95d43b73d400"

# Alibaba Cloud Real-time Audio API Configuration
# 根据阿里云实时语音API文档，使用Token认证

ALIBABA_CLOUD_REGION = "cn-beijing"
ALIBABA_CLOUD_ENDPOINT = "wss://nls-gateway.cn-shanghai.aliyuncs.com/ws/v1"

# Channels Configuration
ASGI_APPLICATION = "E100DictServer.asgi.application"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Django REST Framework + Simple JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}


# Cache configuration — use Redis for nonce storage and other caching
# Install dependency: pip install django-redis
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

CHATBOT_BACKEND = "BRTC" #(Options: "QWEN" or "BRTC")
BRTC_APP_ID = "appsd9wbv9a0vuw"
BRTC_AK = "ALTAKmIrCwULTQ8ENTMkgKNiWi"
BRTC_SK = "c8ab2929d4be44918de7a312249c9587"
BRTC_LIC_KEY = "c705b2e602f94f17a483cd12681e11f3"
BRTC_CONNECTION_METHOD = 1 # 1: Token (REST API, 支持 lang 参数), 2: AK/SK direct (WebSocket 网关, lang 参数可能不生效)
BRTC_ASR_VAD_LEVEL = 20 # 人声检测灵敏度 (范围建议: 更低对小声音敏感，更高抗噪)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'chatbot': {
            'format': '[{asctime}] [{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'chatbot',
        },
    },
    'loggers': {
        'chatbot': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# 尝试启用文件日志（如果失败则只用 console）
try:
    _log_dir = os.path.join(BASE_DIR, 'logs')
    os.makedirs(_log_dir, exist_ok=True)
    LOGGING['handlers']['chatbot_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(_log_dir, 'chatbot.log'),
        'maxBytes': 10 * 1024 * 1024,  # 10 MB
        'backupCount': 5,
        'encoding': 'utf-8',
        'formatter': 'chatbot',
    }
    LOGGING['loggers']['chatbot']['handlers'].append('chatbot_file')
except Exception as e:
    print(f"Warning: Could not configure file logging: {e}")
